youdrive:
  apiHost: https://youdrive.today
  account:
    email: milovtim@ya.ru
    password: FyPfylLFshAW93@w

  logApiHttpRequests: false

spring:
  freemarker:
    cache: false

security:
  basic:
    enabled: true
  user:
    name: u
    password: p
    role: USER
  ignored: /webjars/jquery/3.0.0/jquery.min.js
